export interface CrewMember {
  id: string;
  name: string;
  department: 'Camera' | 'Lighting' | 'Sound' | 'Grip' | 'Art' | 'Production';
  primaryRole: string;
  secondaryRoles: string[];
  location: 'Johannesburg' | 'Cape Town' | 'Durban';
  dayRate: number;
  experienceYears: number;
  avatar: string;
  verified: boolean;
  featured: boolean;
  bio: string;
  skills: string[];
  contactEmail: string;
  phone: string;
}

export interface EquipmentPackage {
  id: string;
  packageName: string;
  category: 'Camera Kit' | 'Lighting Package' | 'Audio Rig' | 'Grip & Motion';
  tier: 'Standard' | 'Pro' | 'Master Cinema';
  dailyRate: number;
  itemCount: number;
  imageUrl: string;
  availability: 'Available' | 'On Set' | 'Maintenance';
  description: string;
  includedItems: string[];
}

export const mockCrewMembers: CrewMember[] = [
  {
    id: 'crew-01',
    name: 'Sipho Dlamini',
    department: 'Camera',
    primaryRole: 'Director of Photography',
    secondaryRoles: ['Camera Operator', 'Steadicam Op'],
    location: 'Johannesburg',
    dayRate: 8500,
    experienceYears: 12,
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=300&auto=format&fit=crop&q=80',
    verified: true,
    featured: true,
    bio: 'Experienced DP specializing in high-end commercials, narrative features, and music videos.',
    skills: ['ARRI Alexa Mini', 'RED V-Raptor', 'Anamorphic Framing', 'Color Grading'],
    contactEmail: 'sipho.d@uprise.co.za',
    phone: '082 123 4567',
  },
  {
    id: 'crew-02',
    name: 'Tanya van der Merwe',
    department: 'Camera',
    primaryRole: '1st Assistant Camera',
    secondaryRoles: ['Focus Puller'],
    location: 'Cape Town',
    dayRate: 4200,
    experienceYears: 8,
    avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=300&auto=format&fit=crop&q=80',
    verified: true,
    featured: false,
    bio: 'Precision focus puller with deep familiarity across wireless follow focus systems and cine optics.',
    skills: ['Preston FI+Z', 'Teradek Bolt 4K', 'Cooke Optics', 'Wireless Video'],
    contactEmail: 'tanya.vdm@uprise.co.za',
    phone: '083 234 5678',
  },
  {
    id: 'crew-03',
    name: 'Kagiso Mokoena',
    department: 'Lighting',
    primaryRole: 'Gaffer',
    secondaryRoles: ['Chief Lighting Technician'],
    location: 'Johannesburg',
    dayRate: 5500,
    experienceYears: 10,
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=300&auto=format&fit=crop&q=80',
    verified: true,
    featured: true,
    bio: 'Versatile gaffer comfortable managing large studio setups and location lighting rigs.',
    skills: ['DMX / CRMX Control', 'Aputure Ecosystem', 'ARRI Skypanels', 'Generator Power'],
    contactEmail: 'kagiso.m@uprise.co.za',
    phone: '084 345 6789',
  },
  {
    id: 'crew-04',
    name: 'David DeCock',
    department: 'Production',
    primaryRole: 'Production Manager',
    secondaryRoles: ['Line Producer'],
    location: 'Johannesburg',
    dayRate: 6000,
    experienceYears: 9,
    avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=300&auto=format&fit=crop&q=80',
    verified: true,
    featured: false,
    bio: 'Logistics hawk managing budgets, call sheets, and gear dispatches for commercials and docs.',
    skills: ['Movie Magic Budgeting', 'Permits & Clearance', 'Fleet Management', 'Call Sheets'],
    contactEmail: 'david.d@uprise.co.za',
    phone: '081 456 7890',
  },
  {
    id: 'crew-05',
    name: 'Nandi Khumalo',
    department: 'Sound',
    primaryRole: 'Location Sound Recordist',
    secondaryRoles: ['Boom Operator', 'Sound Mixer'],
    location: 'Durban',
    dayRate: 4800,
    experienceYears: 6,
    avatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=300&auto=format&fit=crop&q=80',
    verified: true,
    featured: false,
    bio: 'Crisp dialogue recording in complex acoustic environments with multi-channel wireless rigs.',
    skills: ['Sound Devices Scorpio', 'Lectrosonics Wireless', 'Sennheiser MKH416', 'Timecode Sync'],
    contactEmail: 'nandi.k@uprise.co.za',
    phone: '082 567 8901',
  },
  {
    id: 'crew-06',
    name: 'Johan Botes',
    department: 'Grip',
    primaryRole: 'Key Grip',
    secondaryRoles: ['Dolly Grip', 'Rigging Grip'],
    location: 'Cape Town',
    dayRate: 5000,
    experienceYears: 14,
    avatar: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=300&auto=format&fit=crop&q=80',
    verified: true,
    featured: true,
    bio: 'Safety-first key grip with extensive experience on Fisher Dollies and vehicle camera mounts.',
    skills: ['J-L T-Bar Dolly', 'Vehicle Rigs', 'Rigging Safety', 'Truss & Scaffolding'],
    contactEmail: 'johan.b@uprise.co.za',
    phone: '083 678 9012',
  },
  {
    id: 'crew-07',
    name: 'Lerato Naidoo',
    department: 'Art',
    primaryRole: 'Production Designer',
    secondaryRoles: ['Art Director'],
    location: 'Johannesburg',
    dayRate: 6500,
    experienceYears: 11,
    avatar: 'https://images.unsplash.com/photo-1567532939604-b6b5b0db2604?w=300&auto=format&fit=crop&q=80',
    verified: true,
    featured: false,
    bio: 'Creative visionary transforming blank studio spaces into immersive period and sci-fi sets.',
    skills: ['3D Set Rendering', 'Prop Styling', 'Set Construction', 'Color Palette Curation'],
    contactEmail: 'lerato.n@uprise.co.za',
    phone: '084 789 0123',
  },
  {
    id: 'crew-08',
    name: 'Vusi Nkosi',
    department: 'Production',
    primaryRole: 'Assistant Director (1st AD)',
    secondaryRoles: ['Floor Manager'],
    location: 'Johannesburg',
    dayRate: 5800,
    experienceYears: 8,
    avatar: 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=300&auto=format&fit=crop&q=80',
    verified: true,
    featured: true,
    bio: 'Keeps shoots strictly on schedule without compromising creative energy on set.',
    skills: ['Scheduling', 'Crowd Control', 'Set Safety Protocols', 'Breakdowns'],
    contactEmail: 'vusi.n@uprise.co.za',
    phone: '082 890 1234',
  },
  {
    id: 'crew-09',
    name: 'Chloe Bennett',
    department: 'Camera',
    primaryRole: 'Drone Operator / Pilot',
    secondaryRoles: ['Gimbal Tech'],
    location: 'Cape Town',
    dayRate: 5200,
    experienceYears: 5,
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=300&auto=format&fit=crop&q=80',
    verified: true,
    featured: false,
    bio: 'Licensed SACAA drone pilot delivering cinematic aerial tracking shots.',
    skills: ['DJI Inspire 3', 'FPV Cinematic', 'SACAA License', 'Ronin 2 Tuning'],
    contactEmail: 'chloe.b@uprise.co.za',
    phone: '083 901 2345',
  },
  {
    id: 'crew-10',
    name: 'Thabo Mkembe',
    department: 'Lighting',
    primaryRole: 'Best Boy Electric',
    secondaryRoles: ['Spark / Lighting Tech'],
    location: 'Johannesburg',
    dayRate: 3500,
    experienceYears: 6,
    avatar: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=300&auto=format&fit=crop&q=80',
    verified: false,
    featured: false,
    bio: 'Reliable distribution and cable management tech supporting heavy lighting setups.',
    skills: ['Power Distribution', 'Astera Tube Setup', 'Rigging Lamps', 'Safety Grounding'],
    contactEmail: 'thabo.m@uprise.co.za',
    phone: '084 012 3456',
  },
  {
    id: 'crew-11',
    name: 'Anika Reddy',
    department: 'Camera',
    primaryRole: 'DIT (Digital Imaging Technician)',
    secondaryRoles: ['Data Wrangler'],
    location: 'Durban',
    dayRate: 4500,
    experienceYears: 7,
    avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=300&auto=format&fit=crop&q=80',
    verified: true,
    featured: false,
    bio: 'On-set data integrity guardian and live grading specialist.',
    skills: ['Silverstack Lab', 'DaVinci Resolve', 'LTO Tape Archiving', 'RAID Storage'],
    contactEmail: 'anika.r@uprise.co.za',
    phone: '082 111 2233',
  },
  {
    id: 'crew-12',
    name: 'Marcus Botha',
    department: 'Grip',
    primaryRole: 'Best Boy Grip',
    secondaryRoles: ['Rigging Grip'],
    location: 'Cape Town',
    dayRate: 3600,
    experienceYears: 6,
    avatar: 'https://images.unsplash.com/photo-1521119989659-a83eee488004?w=300&auto=format&fit=crop&q=80',
    verified: true,
    featured: false,
    bio: 'Hands-on grip specialized in track laying, overhead flags, and diffusion setups.',
    skills: ['Track Laying', 'C-Stand & Frame Rigs', 'Overhead Silks', 'Safety Cables'],
    contactEmail: 'marcus.b@uprise.co.za',
    phone: '083 222 3344',
  },
  {
    id: 'crew-13',
    name: 'Zanele Sithole',
    department: 'Art',
    primaryRole: 'Wardrobe Stylist',
    secondaryRoles: ['Costume Designer'],
    location: 'Johannesburg',
    dayRate: 4200,
    experienceYears: 7,
    avatar: 'https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?w=300&auto=format&fit=crop&q=80',
    verified: true,
    featured: false,
    bio: 'Character-focused wardrobe styling across contemporary and period television.',
    skills: ['Continuity Tracking', 'Fabric Sourcing', 'On-set Alterations', 'Moodboards'],
    contactEmail: 'zanele.s@uprise.co.za',
    phone: '084 333 4455',
  },
  {
    id: 'crew-14',
    name: 'Pieter van Zyl',
    department: 'Sound',
    primaryRole: 'Boom Operator',
    secondaryRoles: ['Sound Assistant'],
    location: 'Cape Town',
    dayRate: 3200,
    experienceYears: 5,
    avatar: 'https://images.unsplash.com/photo-1501196354995-cbb51c65aaea?w=300&auto=format&fit=crop&q=80',
    verified: false,
    featured: false,
    bio: 'Agile boom placement avoiding shadows while maintaining optimal axis on talent.',
    skills: ['K-Tek Boom Poles', 'Mic Concealment', 'Wireless Plant Mics', 'Lavalier Wiring'],
    contactEmail: 'pieter.vz@uprise.co.za',
    phone: '082 444 5566',
  },
  {
    id: 'crew-15',
    name: 'Fatima Patel',
    department: 'Production',
    primaryRole: 'Script Supervisor',
    secondaryRoles: ['Continuity Supervisor'],
    location: 'Johannesburg',
    dayRate: 4000,
    experienceYears: 9,
    avatar: 'https://images.unsplash.com/photo-1573497019940-1c28c88b4f3e?w=300&auto=format&fit=crop&q=80',
    verified: true,
    featured: false,
    bio: 'Meticulous eye for continuity, axis lines, and editor-ready lined scripts.',
    skills: ['ScriptE Digital', 'Line Cut Logs', 'Timing & Pacing', 'Screen Direction'],
    contactEmail: 'fatima.p@uprise.co.za',
    phone: '083 555 6677',
  },
  {
    id: 'crew-16',
    name: 'Willem Pretorius',
    department: 'Camera',
    primaryRole: '2nd Assistant Camera',
    secondaryRoles: ['Clapper Loader'],
    location: 'Johannesburg',
    dayRate: 2800,
    experienceYears: 3,
    avatar: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=300&auto=format&fit=crop&q=80',
    verified: true,
    featured: false,
    bio: 'Fast slate operation, camera battery management, and organized media handoffs.',
    skills: ['Smart Slating', 'Battery Management', 'Lens Cleaning', 'Camera Reports'],
    contactEmail: 'willem.p@uprise.co.za',
    phone: '084 666 7788',
  },
  {
    id: 'crew-17',
    name: 'Nomvula Zulu',
    department: 'Art',
    primaryRole: 'Makeup Artist (MUA)',
    secondaryRoles: ['SFX Makeup'],
    location: 'Durban',
    dayRate: 3800,
    experienceYears: 6,
    avatar: 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?w=300&auto=format&fit=crop&q=80',
    verified: true,
    featured: false,
    bio: 'High-definition camera makeup, sweat control, and prosthetic application.',
    skills: ['HD Airbrushing', 'Prosthetics', 'Skin Prep', 'Tattoo Coverage'],
    contactEmail: 'nomvula.z@uprise.co.za',
    phone: '082 777 8899',
  },
  {
    id: 'crew-18',
    name: 'Gareth Evans',
    department: 'Lighting',
    primaryRole: 'Console Programmer',
    secondaryRoles: ['Gaffer Assistant'],
    location: 'Cape Town',
    dayRate: 4800,
    experienceYears: 7,
    avatar: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=300&auto=format&fit=crop&q=80',
    verified: true,
    featured: false,
    bio: 'GrandMA and Luminair expert for dynamic lighting cues on commercial sets.',
    skills: ['GrandMA3', 'Luminair', 'CRMX Transmitters', 'Pixel Mapping'],
    contactEmail: 'gareth.e@uprise.co.za',
    phone: '083 888 9900',
  },
  {
    id: 'crew-19',
    name: 'Bongani Mabaso',
    department: 'Grip',
    primaryRole: 'Crane Operator',
    secondaryRoles: ['Key Grip'],
    location: 'Johannesburg',
    dayRate: 5400,
    experienceYears: 12,
    avatar: 'https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?w=300&auto=format&fit=crop&q=80',
    verified: true,
    featured: true,
    bio: 'Fluid tracking moves with heavy jib arms and telescopic camera cranes.',
    skills: ['Jimmy Jib', 'Technocrane Operation', 'Counterweight Calc', 'Remote Heads'],
    contactEmail: 'bongani.m@uprise.co.za',
    phone: '084 999 0011',
  },
  {
    id: 'crew-20',
    name: 'Jessica Taylor',
    department: 'Production',
    primaryRole: 'Production Coordinator',
    secondaryRoles: ['Travel & Logistics Manager'],
    location: 'Cape Town',
    dayRate: 3400,
    experienceYears: 4,
    avatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=300&auto=format&fit=crop&q=80',
    verified: true,
    featured: false,
    bio: 'Smooth crew accommodation, movement, permits, and gear dispatch coordination.',
    skills: ['Vendor Relations', 'Flight & Hotel Bookings', 'Purchase Orders', 'Catering Sync'],
    contactEmail: 'jessica.t@uprise.co.za',
    phone: '082 000 1122',
  },
];

export const mockEquipmentPackages: EquipmentPackage[] = [
  {
    id: 'pkg-01',
    packageName: 'ARRI Alexa Mini LF Cinema Kit',
    category: 'Camera Kit',
    tier: 'Master Cinema',
    dailyRate: 14500,
    itemCount: 12,
    imageUrl: 'https://images.unsplash.com/photo-1585829365295-ab7cd400c167?w=600&auto=format&fit=crop&q=80',
    availability: 'Available',
    description: 'Full Large-Format cinema package ready for principal photography.',
    includedItems: [
      'ARRI Alexa Mini LF Body (LPL Mount)',
      'ARRI MVF-2 Viewfinder',
      'Cooke S4/i Prime Set (25, 32, 50, 75, 100mm)',
      'Wooden Camera Master Top Handle & Cage',
      '4x Codex Compact Drive 1TB',
      'Codex Compact Drive Reader',
      'SmallHD Cine 7 On-Camera Monitor',
      'Teradek Bolt 4K LT 750 Transmitter/Receiver',
      'ARRI Hi-5 Wireless Lens Control Kit',
      'Bright Tangerine Misfit Mattebox',
      '4x Bebob V-Mount Batteries & Quad Charger',
      'OConnor 2560 Fluid Head & Carbon Tripod',
    ],
  },
  {
    id: 'pkg-02',
    packageName: 'RED V-Raptor 8K VV Production Package',
    category: 'Camera Kit',
    tier: 'Pro',
    dailyRate: 11000,
    itemCount: 9,
    imageUrl: 'https://images.unsplash.com/photo-1512790182412-b19e6d62bc39?w=600&auto=format&fit=crop&q=80',
    availability: 'Available',
    description: 'High-frame-rate 8K cinema beast designed for high-end commercials and sports tracking.',
    includedItems: [
      'RED V-Raptor 8K VV Body',
      'Canon RF-to-PL Adapter with ND Filter',
      'Sigma Cine High-Speed Primes (20, 24, 35, 50, 85mm)',
      'DSMC3 RED Touch 7.0" LCD Monitor',
      '2x RED PRO CFexpress 2TB Cards & Reader',
      'Core SWX Micro V-Mount Battery Pack (4x 98Wh)',
      'Tilta Camera Cage & Top Rigging',
      'Sachtler Cine 15 Fluid Head Tripod System',
      'Pelican Storm Transport Cases',
    ],
  },
  {
    id: 'pkg-03',
    packageName: 'Sony FX6 Run-and-Gun Doc Kit',
    category: 'Camera Kit',
    tier: 'Standard',
    dailyRate: 4500,
    itemCount: 7,
    imageUrl: 'https://images.unsplash.com/photo-1589872782415-b6e2002d69e8?w=600&auto=format&fit=crop&q=80',
    availability: 'On Set',
    description: 'Lightweight full-frame setup with internal ND and autofocus for fast-paced field work.',
    includedItems: [
      'Sony FX6 Cinema Body',
      'Sony FE 24-70mm f/2.8 GM II Lens',
      'Sony FE 70-200mm f/2.8 GM OSS II',
      '2x Sony Tough 160GB CEA-G CFexpress Cards',
      'Atomos Ninja V 5" Monitor/Recorder',
      '4x BP-U60 Batteries & Charger',
      'Sennheiser MKE 600 Shotgun Mic',
    ],
  },
  {
    id: 'pkg-04',
    packageName: 'Aputure Commercial Daylight & RGB LED Truck Package',
    category: 'Lighting Package',
    tier: 'Pro',
    dailyRate: 9500,
    itemCount: 14,
    imageUrl: 'https://images.unsplash.com/photo-1524178232363-1fb2b075b655?w=600&auto=format&fit=crop&q=80',
    availability: 'Available',
    description: 'Comprehensive high-output LED package controlled via Sidus Link / CRMX.',
    includedItems: [
      '1x Aputure Electro Storm CS15 RGB (1500W)',
      '2x Aputure LS 600d Pro Daylight Point Source',
      '2x Aputure LS 300x Bi-Color Lights',
      '4x Aputure Amaran T4c RGB Tube Lights',
      'Aputure F10 Fresnel & Barn Doors',
      '2x Light Dome III Softboxes',
      'C-Stands (8x) & Combo Stands (4x)',
      'Power Distribution Cables & Sandbags',
    ],
  },
  {
    id: 'pkg-05',
    packageName: 'ARRI Skypanel S60-C Soft Light Duo',
    category: 'Lighting Package',
    tier: 'Standard',
    dailyRate: 5200,
    itemCount: 6,
    imageUrl: 'https://images.unsplash.com/photo-1517457373958-b7bdd4587205?w=600&auto=format&fit=crop&q=80',
    availability: 'Available',
    description: 'Industry-standard soft light source for studio backdrops and talent key lighting.',
    includedItems: [
      '2x ARRI SkyPanel S60-C Color LED Panels',
      '2x Power Supply Units & Rail Mounts',
      '2x Chimera Softboxes with Grid',
      '2x Heavy Duty Master Combo Stands',
      '2x 10m Power Cables',
      'Flight Cases with Wheels',
    ],
  },
  {
    id: 'pkg-06',
    packageName: 'Sound Devices Scorpio 32-Track Location Rig',
    category: 'Audio Rig',
    tier: 'Master Cinema',
    dailyRate: 6200,
    itemCount: 11,
    imageUrl: 'https://images.unsplash.com/photo-1590602847861-f357a9332bbc?w=600&auto=format&fit=crop&q=80',
    availability: 'Available',
    description: 'Top-tier field recorder setup capable of managing large ensemble cast dialogue.',
    includedItems: [
      'Sound Devices Scorpio 32-Track Field Recorder',
      '4x Lectrosonics Digital Wireless Receivers',
      '6x Lectrosonics SSM Wireless Transmitters',
      '6x Sanken COS-11D Lavalier Microphones',
      'Sennheiser MKH 416 Shotgun Mic with Rycote Blimp',
      'Sennheiser MKH 50 Hypercardioid Mic',
      'K-Tek Carbon Fiber Boom Pole (12ft)',
      '3x Ambient NanoLockit Timecode Boxes',
      'Orca Harness & Sound Bag',
    ],
  },
  {
    id: 'pkg-07',
    packageName: 'DJI Ronin 2 3-Axis Stabilizer Master Combo',
    category: 'Grip & Motion',
    tier: 'Pro',
    dailyRate: 4800,
    itemCount: 8,
    imageUrl: 'https://images.unsplash.com/photo-1564466809058-bf81182fe920?w=600&auto=format&fit=crop&q=80',
    availability: 'Maintenance',
    description: 'Heavy-payload gimbal supporting full cinema cameras up to 13.6 kg.',
    includedItems: [
      'DJI Ronin 2 Gimbal Head',
      'Ronin 2 Remote Controller',
      '6x TB50 Intelligent Batteries & Quad Hub',
      'Cinemilled Counterweights & Steadi-Plate',
      'Ready Rig GS Stabilizer Vest with ProArms',
      'Motion Grip Ring & Top Handle',
      'Hard Transport Case',
    ],
  },
  {
    id: 'pkg-08',
    packageName: 'Fisher 10 Precision Camera Dolly Rig',
    category: 'Grip & Motion',
    tier: 'Master Cinema',
    dailyRate: 7500,
    itemCount: 7,
    imageUrl: 'https://images.unsplash.com/photo-1485846234645-a62644f84728?w=600&auto=format&fit=crop&q=80',
    availability: 'Available',
    description: 'Smooth hydraulic lift dolly for silent and precise camera movement on track or floor.',
    includedItems: [
      'J-L Fisher Model 10 Dolly Body',
      'Hydraulic Lift Arm & Steering Bar',
      '40ft Straight Precision Track',
      '10ft Curved Track Section',
      'Low Board, Running Boards & Side Seats',
      'Leveling Wedges & Track Crate',
    ],
  },
  {
    id: 'pkg-09',
    packageName: 'Wireless Video VideoVillage System',
    category: 'Camera Kit',
    tier: 'Standard',
    dailyRate: 3800,
    itemCount: 6,
    imageUrl: 'https://images.unsplash.com/photo-1526170375885-4d8ecf77b99f?w=600&auto=format&fit=crop&q=80',
    availability: 'Available',
    description: 'Client and director monitoring setup with zero-delay wireless feed.',
    includedItems: [
      '1x Teradek Bolt 4K MAX Transmitter',
      '2x Teradek Bolt 4K Receivers',
      '1x SmallHD 1703 P3 17" High-Bright Director Monitor',
      '1x SmallHD 703 UltraBright Handheld Wireless Monitor',
      'C-Stand Mounts & Sunhoods',
      '4x Gold-Mount Power Plates & AC Supplies',
    ],
  },
];